# Generated by Django 5.2.1 on 2025-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Изображение проекта'),
        ),
    ]
