# Generated by Django 5.2.1 on 2025-06-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0003_portfolioproject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Изображение для статьи'),
        ),
    ]
