# Generated by Django 5.2.1 on 2025-06-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0004_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='atelier.service', verbose_name='Родительская услуга'),
        ),
    ]
