# Generated by Django 5.2.1 on 2025-06-23 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0005_service_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('exam_date', models.DateTimeField(verbose_name='Дата и время проведения экзамена')),
                ('task_image', models.ImageField(blank=True, null=True, upload_to='exam_tasks/', verbose_name='Изображение с заданием')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('examinees', models.ManyToManyField(blank=True, related_name='exams_to_take', to=settings.AUTH_USER_MODEL, verbose_name='Участники экзамена')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['-exam_date'],
            },
        ),
    ]
