# Generated by Django 5.2.1 on 2025-06-23 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0006_mfexam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mfexam',
            options={'ordering': ['-exam_date'], 'verbose_name': 'Экзамен (MF)', 'verbose_name_plural': 'Экзамены (MF)'},
        ),
        migrations.AlterField(
            model_name='mfexam',
            name='examinees',
            field=models.ManyToManyField(blank=True, related_name='mfexams_to_take', to=settings.AUTH_USER_MODEL, verbose_name='Участники экзамена'),
        ),
    ]
