# Generated by Django 5.2.1 on 2025-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Изображение услуги'),
        ),
    ]
