# Generated by Django 5.2.1 on 2025-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0008_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='work_report',
            field=models.FileField(blank=True, null=True, upload_to='order_reports/', verbose_name='Отчет по работам'),
        ),
    ]
